version = 1

# Based on hiredis (https://github.com/redis/hiredis)
# See individual files for detailed copyright information.
[[annotations]]
path = "**"
SPDX-FileCopyrightText = "2024-present, libvalkey contributors"
SPDX-License-Identifier = "BSD-3-Clause"

# Files originating from hiredis-vip (https://github.com/vipshop/hiredis-vip)
[[annotations]]
path = [
    "src/cluster.c",
    "include/valkey/cluster.h",
    "src/vkutil.c",
    "src/vkutil.h",
    "src/command.c",
    "src/command.h",
    "src/win32.h",
]
precedence = "aggregate"
SPDX-FileCopyrightText = [
    "2015-2017, Ieshen Zheng <ieshen.zheng at 163 dot com>",
    "2020, Nick <heronr1 at gmail dot com>",
    "2020-2021, Bjorn Svensson <bjorn.a.svensson at est dot tech>",
    "2020-2021, Viktor Söderqvist <viktor.soderqvist at est dot tech>",
    "2021, Red Hat",
]
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = "include/valkey/adapters/qt.h"
SPDX-FileCopyrightText = "2014, Pietro Cerutti <gahr@gahr.ch>"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = "src/ffc.h"
SPDX-FileCopyrightText = "2021, The fast_float authors"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "tests/scripts/simulated-valkey.pl"
SPDX-FileCopyrightText = "2020, Ericsson Software Technology <viktor.soderqvist@est.tech>"
SPDX-License-Identifier = "FSFAP"
