name: Coverity scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1' # Mon 10.00 UTC

permissions:
  contents: read

jobs:
  coverity:
    if: github.repository == 'valkey-io/libvalkey'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@7ca5f46d061ad9aa95863cd9b214dd48edef361d # v1.5.0
      with:
        packages: libevent-dev
        version: 1.0
    - name: Prepare
      run: |
        mkdir build; cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_TLS=ON ..
    - name: Build, scan and report
      uses: vapier/coverity-scan-action@2068473c7bdf8c2fb984a6a40ae76ee7facd7a85 # v1.8.0
      with:
        project: libvalkey
        token: ${{ secrets.COVERITY_TOKEN }}
        email: bjorn.a.svensson@est.tech
        working-directory: build
