name: Coverity scan
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * 1' # Mon 10.00 UTC

permissions:
  contents: read

jobs:
  coverity:
    if: github.repository == 'valkey-io/libvalkey'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Install dependencies
      uses: awalsh128/cache-apt-pkgs-action@553a35bb8ebd9fcabcb1c9451aa4c98e1b4ca8a9 # v1.6.3
      with:
        packages: libevent-dev
        version: 1.0
    - name: Prepare
      run: |
        mkdir build; cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DENABLE_TLS=ON ..
    - name: Build, scan and report
      uses: vapier/coverity-scan-action@1b6fd4eaba6651aa354c9ea7f48caa1710b4e12e # v1.9.0
      with:
        project: libvalkey
        token: ${{ secrets.COVERITY_TOKEN }}
        email: bjorn.a.svensson@est.tech
        working-directory: build
