name: Spellcheck
on:
  workflow_dispatch:
  pull_request:

permissions:
  contents: read

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Run spellcheck
        uses: rojopolis/spellcheck-github-actions@c1934c57e61c734261d7905b525486b12f8eb670 # 0.66.0
        with:
          config_path: .github/spellcheck-settings.yml
          task_name: Markdown
  typos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install typos
        uses: taiki-e/install-action@82cd3e7658a6f96c86c0234aeeda1748937cb0a1 # v2.85.13
        with:
          tool: typos
      - name: Run typos
        run: typos --config=.github/typos.toml
